version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=sqlite
      - DB_SQLITE_VOLUMES=/data
      - GENERIC_TIMEZONE=America/Bogota
      - N8N_SECURE_COOKIE=false
      - WEBHOOK_URL=http://localhost:5678/
    volumes:
      - ./n8n-data:/home/node/.n8n
      - ./shared-data:/data
    networks:
      - rag-network

  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant-data:/qdrant/storage
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge

volumes:
  n8n-data:
  qdrant-data:
  shared-data: